package se.jocke.nb.eslint.options;

import java.io.File;
import java.nio.file.Paths;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import org.openide.util.NbPreferences;
import se.jocke.nb.eslint.Constants;
import se.jocke.nb.eslint.ESLint;

final class ESLintPanel extends javax.swing.JPanel {

    private final ESLintOptionsPanelController controller;

    ESLintPanel(ESLintOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        eslintPathTextField = new javax.swing.JTextField();
        BrowseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        confTextField = new javax.swing.JTextField();
        browseConfButton = new javax.swing.JButton();

        fileChooser.setDialogTitle(org.openide.util.NbBundle.getMessage(ESLintPanel.class, "ESLintPanel.fileChooser.dialogTitle")); // NOI18N
        fileChooser.setFileFilter(null);
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ESLintPanel.class, "ESLintPanel.jLabel1.text")); // NOI18N

        eslintPathTextField.setText(org.openide.util.NbBundle.getMessage(ESLintPanel.class, "ESLintPanel.eslintPathTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(BrowseButton, org.openide.util.NbBundle.getMessage(ESLintPanel.class, "ESLintPanel.BrowseButton.text")); // NOI18N
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ESLintPanel.class, "ESLintPanel.jLabel2.text")); // NOI18N

        confTextField.setText(org.openide.util.NbBundle.getMessage(ESLintPanel.class, "ESLintPanel.confTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(browseConfButton, org.openide.util.NbBundle.getMessage(ESLintPanel.class, "ESLintPanel.browseConfButton.text")); // NOI18N
        browseConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseConfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eslintPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(confTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BrowseButton)
                    .addComponent(browseConfButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eslintPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(confTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseConfButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            eslintPathTextField.setText(fileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_BrowseButtonActionPerformed

    private void browseConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseConfButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            confTextField.setText(fileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_browseConfButtonActionPerformed

    void load() {
        Preferences prefs = NbPreferences.forModule(ESLint.class);
        eslintPathTextField.setText(prefs.get(Constants.ESLINT_PATH, "/usr/local/bin"));
        confTextField.setText(prefs.get(Constants.ESLINT_CONF, Paths.get(System.getProperty("user.home"), ".eslintrc").toString()));
    }

    void store() {
        NbPreferences.forModule(ESLint.class).put(Constants.ESLINT_PATH, eslintPathTextField.getText());
        NbPreferences.forModule(ESLint.class).put(Constants.ESLINT_CONF, confTextField.getText());
    }

    boolean valid() {
        File exec;
        try {
            exec = new File(eslintPathTextField.getText());
        } catch (Exception e) {
            return false;
        }
        return exec.exists() && exec.canExecute();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseButton;
    private javax.swing.JButton browseConfButton;
    private javax.swing.JTextField confTextField;
    private javax.swing.JTextField eslintPathTextField;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
